// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    IMdiFacebook: typeof import('~icons/mdi/facebook')['default']
    IMdiGithub: typeof import('~icons/mdi/github')['default']
    IMdiLinkedin: typeof import('~icons/mdi/linkedin')['default']
  }
}

export { }
